apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: togglemaster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: "https://github.com/gabrielsrisaffi-droid/FIAP.git"
    targetRevision: "fase-3-devsecops-gitops"
    path: k8s/base

  destination:
    server: https://kubernetes.default.svc
    namespace: togglemaster

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true

  revisionHistoryLimit: 5

  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 1m
